irqchip/gicv3-its: fixed build error
Fixed below compiler error:
  | /.../drivers/irqchip/irq-gic-v3-its.c: In function 'its_enable_quirk_mrvl_35443':
  | /.../drivers/irqchip/irq-gic-v3-its.c:4682:12: error: 'struct its_node' has no member named 'device_ids'
  |  4682 |         its->device_ids = 0x14;
  |       |

This issue codes comes from backport of marvell patches, but on the
tree, field device_ids of struct its_node had been removed in previous
commit 576a83429757999f220f36f206044af2b9026672, the fix refer it too.

Signed-off-by: Wenlin Kang <wenlin.kang@windriver.com>