PCI: octeontx-83: fixed compiler error
Fixed build error:
  /.../drivers/pci/controller/pci-octeontx-ecam.c: In function 'octeontx_ecam_probe':
  /.../drivers/pci/controller/pci-octeontx-ecam.c:267:16: error: too many arguments to function 'pci_host_common_probe'
  267 |         return pci_host_common_probe(pdev, &pci_octeontx_ecam_ops);
      |                ^~~~~~~~~~~~~~~~~~~~~
  In file included from /.../drivers/pci/controller/pci-octeontx-ecam.c:15:
   /.../include/linux/pci-ecam.h:65:5: note: declared here
   65 | int pci_host_common_probe(struct platform_device *pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~

This issue comes from backport of marvell patches, and the fix refer
upstream commit b2f75a41eaa6bfc4aa6f6a1faefbf21c2c8d1588

Signed-off-by: Wenlin Kang <wenlin.kang@windriver.com>